blank_issues_enabled: false
contact_links:
  - name: "Latest & Greatest Selfhosted Data"
    url: "https://github.com/latest&greatest-selfhosted/latest&greatest-selfhosted-data/issues"
    about: "Please submit your issues or suggestions to the latest&greatest-selfhosted-data repository instead."
